## TESTING

version: "3.7"

services:
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    #net: hadoop
    volumes:
      - <namenode-volume>:/hadoop/dfs/name
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CLUSTER_NAME=<cluster-name>
  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    ##net: hadoop
    volumes:
      - <datanode-volume>:/hadoop/dfs/data
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    domainname: hadoop
    #net: hadoop
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
  nodemanager1:
    image: uhopper/hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    domainname: hadoop
    #net: hadoop
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020
      - YARN_CONF_yarn_resourcemanager_hostname=<resourcemanager-host>
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs