## TESTING

version: "3.7"

services:
  hadoop-build:
    image: cloudmesh/docker-hadoop
    build: .
    command: "exit 0"
    
  namenode:
    image: cloudmesh/docker-hadoop-namenode
    build: ./namenode
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks:
      - hbase
    volumes:
      - namenode-volume:/hadoop/dfs/name
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CLUSTER_NAME=<cluster-name>
    depends_on:
      - hadoop-build
  datanode:
    image: uhopper/hadoop-datanode
    build: ./datanode
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    networks:
      - hbase
    volumes:
      - datanode-volume:/hadoop/dfs/data
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020
    depends_on:
      - hadoop-build
      - namenode

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    build: ./resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    domainname: hadoop
    networks:
      - hbase
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
    depends_on: 
      - hadoop-build
      - namenode

  nodemanager:
    image: uhopper/hadoop-nodemanager
    build: ./nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    domainname: hadoop
    networks:
      - hbase
    environment:
      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://<namenode-host>:8020
      - YARN_CONF_yarn_resourcemanager_hostname=<resourcemanager-host>
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    depends_on: 
      - hadoop-build
      - namenode

networks:
  hbase:

volumes:
  namenode-volume:
  datanode-volume:
