#Referred https://www.docker.com/blog/simplifying-kubernetes-with-docker-compose-and-friends/

#Specifying the docker-compose version
version: "3.7"

#Specifying the services used by docker
services:
  
  #In order to build a hadoop image
  hadoop:
    image: dockerdemos/lab-web
    ports:
     - "33000:80"
  
  #In order to build a spark image
  spark:
    image: dockerdemos/lab-words
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
  db:
    image: dockerdemos/lab-db